apiVersion: v1
kind: Secret
metadata:
  name: operator-grafana-credentials
  namespace: integration
type: Opaque
stringData:
  username: integration-admin
  password: integration-admin-password
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: integration-grafana
  namespace: integration
spec:
  external:
    url: http://grafana.integration.svc.cluster.local:3000
    adminUser:
      name: operator-grafana-credentials
      key: username
    adminPassword:
      name: operator-grafana-credentials
      key: password
